### ISSUE TITLE
Demo returns 500 when SVG selected

### ISSUE THREAD

**Issue by metakermit** [ihabunek/hub3-api#2]
Hey, I bumped into a 500 when I try to run your [demo request](https://hub3.bigfish.software/api/v1/demo) with the SVG option.

BTW, do you maybe know of an existing example of how to generate the HUB3 image directly in Python using your [pdf417-py](https://github.com/ihabunek/pdf417-py) library? I don't feel like going through the spec document if you or someone else already prepared a higher-level function that exposes an interface similar to your API.

Pozdrav 😊

**Comment by ihabunek** [comment]
Cannot reproduce it at the moment. Did you change the demo input when you got the error? I should really plug Sentry into the project...

This API is PHP based since that's the first implementation I made. I don't have a HUB3 implementation in Python, but it's really pretty trivial. The spec is only a couple of pages:
http://www.hub.hr/sites/default/files/2dbc_0.pdf

**Comment by ihabunek** [comment]
OK, I figured it out. SVG output did not work. I moved to a new server and did not have the xml extension installed.

**Comment by metakermit** [comment]
Wow, that was fast. Thanks 😄
